[build]
  base = "."
  publish = "target"
  command = "mvn clean package -DskipTests"

[build.environment]
  JAVA_VERSION = "17"
  MAVEN_VERSION = "3.8.6"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { DATABASE_URL = "jdbc:postgresql://localhost:5432/gardenuniversity", DATABASE_DRIVER = "org.postgresql.Driver", DATABASE_PLATFORM = "org.hibernate.dialect.PostgreSQLDialect" }

[context.deploy-preview]
  environment = { DATABASE_URL = "jdbc:h2:mem:gardenuniversity", DATABASE_DRIVER = "org.h2.Driver", DATABASE_PLATFORM = "org.hibernate.dialect.H2Dialect" }
