[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmd = "./mvnw clean package -DskipTests -Dmaven.test.skip=true"

[phases.start]
cmd = "java -Dserver.port=$PORT -Dserver.address=0.0.0.0 -Dspring.profiles.active=prod -Xmx512m -jar target/garden-university-system-0.0.1-SNAPSHOT.jar"
