[build]
  publish = "static"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  JAVA_VERSION = "17"
  MAVEN_VERSION = "3.9.0"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8080/api/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "http://localhost:8080/login"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "http://localhost:8080/dashboard"
  status = 200

[[redirects]]
  from = "/alumnos"
  to = "http://localhost:8080/alumnos"
  status = 200

[[redirects]]
  from = "/docentes"
  to = "http://localhost:8080/docentes"
  status = 200

[[redirects]]
  from = "/administrativos"
  to = "http://localhost:8080/administrativos"
  status = 200

[[redirects]]
  from = "/programas"
  to = "http://localhost:8080/programas"
  status = 200

[[redirects]]
  from = "/materias"
  to = "http://localhost:8080/materias"
  status = 200

[[redirects]]
  from = "/asignaciones"
  to = "http://localhost:8080/asignaciones"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  SPRING_PROFILES_ACTIVE = "prod"
  
[context.deploy-preview.environment]
  SPRING_PROFILES_ACTIVE = "dev"
