[build]
  # IMPORTANTE: Comando completamente vacío para sitio estático
  command = ""
  
  # Directorio base donde están nuestros archivos (SOLO este directorio)
  base = "netlify-deploy/"
  
  # Directorio de publicación (relativo al base)
  publish = "."
  
  # Ignorar cambios en otros directorios para evitar rebuilds innecesarios
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- netlify-deploy/ || exit 0"

[build.environment]
  # Forzar desactivación de todas las auto-detecciones
  DISABLE_PREBUILD = "true"
  NODE_VERSION = "18"
  # Variables para desactivar Maven completamente
  MAVEN_OPTS = ""
  JAVA_HOME = ""

# Configuración de redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data:; connect-src 'self';"

# Configuración para archivos específicos
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
